# Generated by Django 4.0.3 on 2022-04-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_message_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='sender_email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='sender_name',
        ),
    ]
