# Generated by Django 4.0.3 on 2022-03-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_features_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features_image',
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
